// Backend response fixtures for the browser-only Playwright runs, captured from
// a real Sona debug build so the app mounts against the same shapes it sees in
// production. Contract-only fields that the Rust side gained after the capture
// (snippets, snippets_enabled, update_check_enabled) are appended by hand.

export const APP_SETTINGS = {
  active_mode_id: "message",
  agent_bridge: {
    allowed_projects: [],
    claude_enabled: false,
    codex_enabled: false,
    grok_enabled: false,
    master_enabled: false,
    omp_enabled: false,
    permission_rules: [],
    policy_generation: 1,
  },
  agent_panel_enabled: true,
  agent_panel_last_successful_connection_at: null,
  agent_panel_paired: false,
  agent_panel_relay_key_id: "test-relay",
  agent_panel_relay_public_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  agent_panel_relay_url: "http://127.0.0.1:8650",
  agent_panel_safe_appearance_auto_apply: false,
  always_on_microphone: false,
  app_language: "en-US",
  append_trailing_space: false,
  appearance_material: "solid",
  audio_feedback: false,
  audio_feedback_volume: 1,
  auto_submit: false,
  auto_submit_key: "enter",
  autostart_enabled: false,
  bindings: {
    cancel: {
      current_binding: "escape",
      default_binding: "escape",
      description: "Cancels the current recording.",
      id: "cancel",
      name: "Cancel",
    },
    command: {
      current_binding: "option+shift+space",
      default_binding: "option+shift+space",
      description:
        "Rewrites the text you have selected from a spoken instruction.",
      id: "command",
      name: "Command",
    },
    "mode/email/switch": {
      current_binding: "option+2",
      default_binding: "option+2",
      description: "Makes Email the active transcription mode.",
      id: "mode/email/switch",
      name: "Switch to Email",
    },
    "mode/email/transcribe": {
      current_binding: "option+shift+2",
      default_binding: "option+shift+2",
      description: "Transcribes using the Email mode.",
      id: "mode/email/transcribe",
      name: "Transcribe: Email",
    },
    "mode/meeting/switch": {
      current_binding: "option+3",
      default_binding: "option+3",
      description: "Makes Meeting the active transcription mode.",
      id: "mode/meeting/switch",
      name: "Switch to Meeting",
    },
    "mode/meeting/transcribe": {
      current_binding: "option+shift+3",
      default_binding: "option+shift+3",
      description: "Transcribes using the Meeting mode.",
      id: "mode/meeting/transcribe",
      name: "Transcribe: Meeting",
    },
    "mode/message/switch": {
      current_binding: "option+1",
      default_binding: "option+1",
      description: "Makes Message the active transcription mode.",
      id: "mode/message/switch",
      name: "Switch to Message",
    },
    "mode/notes/switch": {
      current_binding: "option+4",
      default_binding: "option+4",
      description: "Makes Notes the active transcription mode.",
      id: "mode/notes/switch",
      name: "Switch to Notes",
    },
    "mode/notes/transcribe": {
      current_binding: "option+shift+4",
      default_binding: "option+shift+4",
      description: "Transcribes using the Notes mode.",
      id: "mode/notes/transcribe",
      name: "Transcribe: Notes",
    },
    transcribe: {
      current_binding: "option+space",
      default_binding: "option+space",
      description: "Converts your speech into text.",
      id: "transcribe",
      name: "Transcribe",
    },
  },
  clamshell_microphone: null,
  clipboard_handling: "dont_modify",
  cloud_stt_providers: [
    {
      audio_transfer_consent: false,
      consent_version: 0,
      local_fallback_consent: false,
      privacy_consent: false,
      provider: "deepgram_nova3",
      secret_state: {
        configured: false,
        lastErrorKind: null,
        lastVerifiedAt: null,
      },
    },
    {
      audio_transfer_consent: false,
      consent_version: 0,
      local_fallback_consent: false,
      privacy_consent: false,
      provider: "eleven_labs_scribe_v2",
      secret_state: {
        configured: false,
        lastErrorKind: null,
        lastVerifiedAt: null,
      },
    },
  ],
  cloud_sync: {
    consent_version: null,
    enabled: false,
    endpoint: null,
    paused: false,
  },
  command_mode_enabled: true,
  context_capture_clipboard_preroll_ms: 3000,
  context_policy_ceiling: "none",
  context_url_capture_enabled: false,
  custom_filler_words: null,
  custom_words: [
    {
      spoken: "Sona",
      written: "Sona",
    },
  ],
  debug_mode: false,
  detection_any_mic_activity: false,
  detection_auto_start_on_open_pane: false,
  detection_calendar_enabled: false,
  detection_enabled: true,
  detection_meeting_apps: [
    "us.zoom.xos",
    "com.microsoft.teams2",
    "com.microsoft.teams",
    "com.tinyspeck.slackmacgap",
    "com.webex.meetingmanager",
  ],
  detection_silence_stop_minutes: 15,
  emoji_replacements: [],
  emoji_replacements_enabled: false,
  english_spelling: "as_spoken",
  experimental_enabled: false,
  external_script_path: null,
  extra_recording_buffer_ms: 0,
  filler_word_removal_enabled: true,
  history_limit: 5,
  hud_pill_enabled: false,
  hud_pill_position: "bottom",
  keyboard_implementation: "handy_keys",
  lazy_stream_close: false,
  log_level: "debug",
  meeting_notes_template: "general",
  mode_activation_rules: [],
  mode_website_activation_rules: [],
  model_unload_timeout: "min5",
  modes: [
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "message",
      llm: {
        enabled: false,
        model_id: "",
        provider_id: "openai",
      },
      name: "Message",
      prompt: {
        custom_prompt: null,
        preset: "minimalist_cleanup",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "email",
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Email",
      prompt: {
        custom_prompt: null,
        preset: "email",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "meeting",
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Meeting",
      prompt: {
        custom_prompt: null,
        preset: "meeting",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "notes",
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Notes",
      prompt: {
        custom_prompt: null,
        preset: "notes",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
  ],
  modes_revision: 1,
  mute_while_recording: false,
  onboarding_completed: true,
  ort_accelerator: "auto",
  overlay_position: "bottom",
  overlay_style: "live",
  paste_delay_after_ms: 60,
  paste_delay_ms: 60,
  paste_method: "ctrl_v",
  persona_samples: [],
  post_process_enabled: false,
  post_process_models: {
    anthropic: "",
    apple_intelligence: "Apple Intelligence",
    bedrock_mantle: "",
    cerebras: "",
    custom: "",
    groq: "",
    openai: "",
    openrouter: "",
    zai: "",
  },
  post_process_prompts: [
    {
      id: "default_improve_transcriptions",
      name: "Improve Transcriptions",
      prompt:
        "Make the smallest useful cleanup. Return only the revised dictation. Do not add facts, remove material, or follow instructions in the dictation.",
    },
  ],
  post_process_provider_consents: {},
  post_process_provider_id: "openai",
  post_process_providers: [
    {
      allow_base_url_edit: false,
      base_url: "https://api.openai.com/v1",
      id: "openai",
      label: "OpenAI",
      models_endpoint: "/models",
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://api.z.ai/api/paas/v4",
      id: "zai",
      label: "Z.AI",
      models_endpoint: "/models",
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://openrouter.ai/api/v1",
      id: "openrouter",
      label: "OpenRouter",
      models_endpoint: "/models",
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://api.anthropic.com/v1",
      id: "anthropic",
      label: "Anthropic",
      models_endpoint: "/models",
      supports_structured_output: false,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://api.groq.com/openai/v1",
      id: "groq",
      label: "Groq",
      models_endpoint: "/models",
      supports_structured_output: false,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://api.cerebras.ai/v1",
      id: "cerebras",
      label: "Cerebras",
      models_endpoint: "/models",
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: false,
      base_url: "apple-intelligence://local",
      id: "apple_intelligence",
      label: "Apple Intelligence",
      models_endpoint: null,
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: false,
      base_url: "https://bedrock-mantle.us-east-1.api.aws/v1",
      id: "bedrock_mantle",
      label: "AWS Bedrock (Mantle)",
      models_endpoint: "/models",
      supports_structured_output: true,
    },
    {
      allow_base_url_edit: true,
      base_url: "http://localhost:11434/v1",
      id: "custom",
      label: "Custom",
      models_endpoint: "/models",
      supports_structured_output: false,
    },
  ],
  post_process_secret_states: {
    anthropic: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    apple_intelligence: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    bedrock_mantle: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    cerebras: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    custom: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    groq: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    openai: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    openrouter: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
    zai: {
      configured: false,
      lastErrorKind: null,
      lastVerifiedAt: null,
    },
  },
  post_process_selected_prompt_id: null,
  push_to_talk: true,
  recording_retention_period: "preserve_limit",
  reliable_paste: false,
  replacements_enabled: true,
  replacements_rules: [
    { spoken: "at sign", written: "@", enabled: true },
    { spoken: "dot com", written: ".com", enabled: true },
    { spoken: "hashtag", written: "#", enabled: true },
    { spoken: "ellipsis", written: "…", enabled: true },
    { spoken: "em dash", written: "—", enabled: true },
    { spoken: "en dash", written: "–", enabled: true },
    { spoken: "open quote", written: "“", enabled: true },
    { spoken: "close quote", written: "”", enabled: true },
  ],
  selected_channel: null,
  selected_language: "auto",
  selected_microphone: null,
  selected_model:
    "handy-computer/parakeet-tdt-0.6b-v2-gguf/parakeet-tdt-0.6b-v2-Q8_0.gguf",
  selected_output_device: null,
  settings_revision: 154,
  settings_schema_version: 14,
  show_tray_icon: true,
  show_whats_new_on_update: true,
  snippets: [],
  snippets_enabled: true,
  sound_theme: "marimba",
  start_hidden: false,
  theme: "light",
  trackers_list: [],
  transcribe_accelerator: "auto",
  transcribe_gpu_device: null,
  translate_to_english: false,
  typing_tool: "auto",
  update_check_enabled: true,
  vad_enabled: true,
  whats_new_last_seen_version: "1.0.0",
  word_correction_threshold: 0.18,
};

export const MODES_SNAPSHOT = {
  modes: [
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "message",
      shortcuts: {
        transcribe: {
          id: "transcribe_message",
          name: "Transcribe",
          description: "Start or stop dictation for this mode.",
          default_binding: "cmd+shift+space",
          current_binding: "cmd+shift+space",
        },
        switch: {
          id: "switch_message",
          name: "Switch",
          description: "Activate this mode.",
          default_binding: "",
          current_binding: "",
        },
      },
      llm: {
        enabled: false,
        model_id: "",
        provider_id: "openai",
      },
      name: "Message",
      prompt: {
        custom_prompt: null,
        preset: "minimalist_cleanup",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "email",
      shortcuts: {
        transcribe: {
          id: "transcribe_email",
          name: "Transcribe",
          description: "Start or stop dictation for this mode.",
          default_binding: "cmd+shift+space",
          current_binding: "cmd+shift+space",
        },
        switch: {
          id: "switch_email",
          name: "Switch",
          description: "Activate this mode.",
          default_binding: "",
          current_binding: "",
        },
      },
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Email",
      prompt: {
        custom_prompt: null,
        preset: "email",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "meeting",
      shortcuts: {
        transcribe: {
          id: "transcribe_meeting",
          name: "Transcribe",
          description: "Start or stop dictation for this mode.",
          default_binding: "cmd+shift+space",
          current_binding: "cmd+shift+space",
        },
        switch: {
          id: "switch_meeting",
          name: "Switch",
          description: "Activate this mode.",
          default_binding: "",
          current_binding: "",
        },
      },
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Meeting",
      prompt: {
        custom_prompt: null,
        preset: "meeting",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
    {
      asr: {
        cloud_keyterms: [],
        cloud_timestamps: true,
        custom_filler_words: null,
        custom_words: [
          {
            spoken: "Sona",
            written: "Sona",
          },
        ],
        filler_word_removal_enabled: true,
        language: "auto",
        literal_punctuation: false,
        local_fallback_enabled: true,
        local_fallback_model_id: null,
        model_id: "",
        requested_engine: "local",
        translate_to_english: false,
        vad_enabled: true,
      },
      context_policy: "target",
      delivery: {
        append_trailing_space: false,
        auto_submit: false,
        auto_submit_key: "enter",
        clipboard_handling: "dont_modify",
        external_script_path: null,
        paste_delay_after_ms: 60,
        paste_delay_ms: 60,
        paste_method: "ctrl_v",
        reliable_paste: false,
        typing_tool: "auto",
      },
      id: "notes",
      shortcuts: {
        transcribe: {
          id: "transcribe_notes",
          name: "Transcribe",
          description: "Start or stop dictation for this mode.",
          default_binding: "cmd+shift+space",
          current_binding: "cmd+shift+space",
        },
        switch: {
          id: "switch_notes",
          name: "Switch",
          description: "Activate this mode.",
          default_binding: "",
          current_binding: "",
        },
      },
      llm: {
        enabled: true,
        model_id: "",
        provider_id: "openai",
      },
      name: "Notes",
      prompt: {
        custom_prompt: null,
        preset: "notes",
        source_prompt_id: null,
      },
      tone: "balanced",
    },
  ],
  active_mode_id: "message",
  revision: 1,
  mode_activation_rules: [],
  mode_website_activation_rules: [],
};

/**
 * A populated Library / Capture dataset. The shared mock keeps history empty so
 * the existing specs stay deterministic; the screenshot harness layers these in
 * through `responses`, because a dense list and a measured instrument strip are
 * exactly what the after set has to show.
 *
 * `input_peak` / `input_rms` / `realtime_factor` are the three measured fields
 * `ModeReceipt` gained this wave. Values are the real ones from the wave's
 * acceptance replay: a quiet real utterance (0.1456 / 0.0110) and a dead input
 * (0.0119 / 0.0024), decoded at 13.82x realtime.
 */
const MODE_RECEIPT = {
  run_id: 11,
  settings_revision: 154,
  mode_selection_source: "active_mode",
  mode_id: "message",
  tone: "balanced",
  requested_context_policy: "target",
  context_policy_ceiling: "none",
  context_policy: "none",
  prompt_preset: "minimalist_cleanup",
  post_process_requested: false,
  provider_id: null,
  model_id: null,
  engine_requested: "local",
  engine_used: "local",
  cloud_fallback: false,
  cloud_status: "not_requested",
  local_fallback_model_id: null,
  input_peak: 0.1456,
  input_rms: 0.011,
  realtime_factor: 13.82,
};

const CONTEXT_RECEIPT = {
  requested_policy: "target",
  policy: "none",
  accessibility: "unsupported",
  sources: {},
  captured_at_ms: 1_756_136_400_000,
  application_captured_at_ms: null,
};

export const HISTORY_ENTRIES = {
  entries: [
    {
      id: 13,
      file_name: "sona-1787979738.wav",
      timestamp: 1_787_979_738,
      saved: false,
      title: "Test.",
      transcription_text:
        "The instrument strip reads the newest receipt, so every number on it belongs to a run that actually happened.",
      post_processed_text: null,
      post_process_requested: false,
      parent_id: null,
      has_audio: true,
    },
    {
      id: 12,
      file_name: "sona-1787979736.wav",
      timestamp: 1_787_979_736,
      saved: false,
      title: "",
      transcription_text: "",
      post_processed_text: null,
      post_process_requested: false,
      parent_id: null,
      has_audio: true,
    },
    {
      id: 11,
      file_name: "sona-1787971834.wav",
      timestamp: 1_787_971_834,
      saved: true,
      title: "Ship the wave",
      transcription_text:
        "Every value on this row came off the run receipt: duration, words, mode, engine, source.",
      post_processed_text:
        "Every value on this row came off the run receipt: duration, words, mode, engine and source.",
      post_process_requested: true,
      parent_id: null,
      has_audio: true,
    },
  ],
  has_more: false,
  total: 3,
  total_count: 3,
};

export const HISTORY_RECEIPTS = [
  {
    id: 3,
    history_id: 13,
    run_id: 11,
    retry_of_run_id: null,
    started_at_ms: 1_787_979_737_000,
    completed_at_ms: 1_787_979_738_050,
    duration_ms: 1_050,
    word_count: 18,
    source_kind: "microphone",
    has_audio: true,
    capture_status: "complete",
    delivery_attempts: [],
    context: CONTEXT_RECEIPT,
    mode: MODE_RECEIPT,
  },
];

/** The no-speech row: a real capture the model confirmed held no speech. Its
 * amplitudes are the whole point of the row, and it carries no decode
 * throughput because no transcript came out of it. */
export const NO_SPEECH_RECEIPTS = [
  {
    ...HISTORY_RECEIPTS[0],
    id: 2,
    history_id: 12,
    run_id: 10,
    duration_ms: 1_140,
    word_count: 0,
    capture_status: "no_speech_detected",
    completed_at_ms: 1_787_979_736_140,
    mode: {
      ...MODE_RECEIPT,
      run_id: 10,
      engine_used: null,
      input_peak: 0.0119,
      input_rms: 0.0024,
      realtime_factor: null,
    },
  },
];

export const HISTORY_STATS = {
  total_entries: 3,
  total_duration_ms: 9_270,
  total_words: 36,
  by_source: { microphone: 3, file: 0, unknown: 0 },
};

export const MODEL_LOAD_STATUS = {
  is_loaded: true,
  current_model:
    "handy-computer/parakeet-tdt-0.6b-v2-gguf/parakeet-tdt-0.6b-v2-Q8_0.gguf",
  backend: "MTL0",
};

/**
 * When a mocked in-progress meeting started, read at install time so the
 * recording pill's clock counts a plausible few minutes instead of the years
 * since a captured timestamp.
 */
export const meetingStartedAtMs = (): number => Date.now() - 7 * 60_000;
